version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  ml_api:
    build:
      context: .           # Set context to the project root
      dockerfile: ml_model/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - MODEL_PATH=crime_prediction_model
    depends_on:
      kafka:
        condition: service_started

  weather_worker:
    build:
      context: .           # Set context to the project root
      dockerfile: weather_service/Dockerfile
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - WEATHER_API_BASE_URL=https://api.open-meteo.com/v1/forecast
    depends_on:
      kafka:
        condition: service_started
